package shopcart

const ERROR_SHOPCART = 0xc0000

const ERROR_SHOPCART_NOT_FOUND_ID = ERROR_SHOPCART + 1

const ERROR_SHOPCART_NOT_FOUND = ERROR_SHOPCART + 2

const ERROR_SHOPCART_NOT_FOUND_UID = ERROR_SHOPCART + 3
